//

//  main.m

//  demo

//

//  Created by demo on 2018/1/23.

//  Copyright © 2018 demo. All rights reserved.

//



#import <UIKit/UIKit.h>

#import "AppDelegate.h"





@interface AllWeatherRadial: NSObject



@property float rainHandling;

@property float snowHandling;



@end



@implementation AllWeatherRadial



@synthesize rainHandling;

@synthesize snowHandling;



- (id) initWithPressure: (float) p

             treadDepth: (float) td

{
    
    if (self = [super init]) {
        
        rainHandling = 23.7;
        
        snowHandling = 42.5;
        
    }
    
    
    
    return (self);
    
    
    
} // initWithPressure:treadDepth



@end



int main(int argc, char * argv[]) {
    
    
    
    @autoreleasepool {
        
        AllWeatherRadial *tire;
        
        
        
        tire = [[AllWeatherRadial alloc] init];
        
        [tire setRainHandling: 20];
        
        [tire setSnowHandling: 28];
        
        
        
        tire.rainHandling = 4;
        
        
        
        /*
         
         __text:0000000100006A04                 FMOV            S0, #4.0
         
         __text:0000000100006A08                 ADRP            X8, #selRef_setRainHandling_@PAGE
         
         __text:0000000100006A0C                 ADD             X8, X8, #selRef_setRainHandling_@PAGEOFF
         
         __text:0000000100006A10                 LDUR            X0, [X29,#var_18]
         
         
         __text:0000000100006A14                 LDR             X1, [X8] ; "setRainHandling:"
         
         */
        
        
        
        
        
        float foo = [tire rainHandling];
        
        
        
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
        
    }
    
}



// no challenge at all.

// although there is no `getter' and `setter' method in source code.

// it is in binary which is generated by the compiler.

